version: '3.8'
services:
  web:
    build: .
    volumes:
      # django static file location after collectstatic
      - ./data/static:/mnt/web/static
      - ./data/media:/mnt/web/media
    environment:
      - DJANGO_SETTINGS_MODULE=handlechat.settings.prod
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/static:/mnt/web/static
      - /etc/ssl:/etc/ssl

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
